# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet(_fromUtf8(""))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.login_page = QtGui.QWidget()
        self.login_page.setObjectName(_fromUtf8("login_page"))
        self.tabWidget = QtGui.QTabWidget(self.login_page)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 741, 341))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(140, 80, 91, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(250, 70, 321, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 150, 321, 27))
        self.lineEdit_2.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(550, 230, 99, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(330, 20, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.line_11 = QtGui.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(17, 40, 711, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.tab)
        self.line_12.setGeometry(QtCore.QRect(10, 190, 711, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_15 = QtGui.QFrame(self.tab)
        self.line_15.setGeometry(QtCore.QRect(70, 50, 20, 151))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.tab)
        self.line_16.setGeometry(QtCore.QRect(640, 50, 20, 151))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.line_18 = QtGui.QFrame(self.tab)
        self.line_18.setGeometry(QtCore.QRect(540, 260, 118, 3))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(100, 160, 31, 17))
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setPixmap(QtGui.QPixmap(_fromUtf8(":/username/ui/c70194b792ea062c5365b619fd3050b3.svg")))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(100, 80, 31, 17))
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setPixmap(QtGui.QPixmap(_fromUtf8(":/username/ui/eeb69a3cb92300456b6a5f4162093851.svg")))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(370, 170, 161, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(370, 110, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(370, 60, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 100, 201, 27))
        self.lineEdit_3.setText(_fromUtf8(""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(530, 100, 201, 27))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(530, 160, 201, 27))
        self.lineEdit_5.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 160, 201, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(350, 40, 20, 171))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 50, 201, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(530, 50, 201, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 250, 99, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_3.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(320, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.line_13 = QtGui.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(10, 30, 711, 20))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.tab_2)
        self.line_14.setGeometry(QtCore.QRect(10, 200, 711, 20))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.label_38 = QtGui.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(20, 250, 531, 41))
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_37 = QtGui.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(20, 230, 68, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 230, 99, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 230, 431, 27))
        self.lineEdit_9.setText(_fromUtf8(""))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(150, 140, 441, 27))
        self.lineEdit_10.setText(_fromUtf8(""))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(30, 150, 68, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(30, 240, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(610, 140, 99, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(30, 200, 681, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(270, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.line_19 = QtGui.QFrame(self.tab_3)
        self.line_19.setGeometry(QtCore.QRect(20, 40, 691, 16))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 180, 451, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(150, 100, 441, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(80, 280, 691, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 60, 441, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(30, 70, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 60, 101, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_39 = QtGui.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(30, 280, 51, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.login_page)
        self.label_3.setGeometry(QtCore.QRect(27, 26, 731, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setIndent(100)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.login_page)
        self.line.setGeometry(QtCore.QRect(20, 60, 741, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.login_page)
        self.line_2.setGeometry(QtCore.QRect(20, 450, 741, 20))
        self.line_2.setStyleSheet(_fromUtf8(""))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.stackedWidget.addWidget(self.login_page)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.tabWidget_2 = QtGui.QTabWidget(self.page)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 781, 531))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 80, 121, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(280, 90, 121, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(550, 90, 101, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(650, 80, 121, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.line_5 = QtGui.QFrame(self.tab_4)
        self.line_5.setGeometry(QtCore.QRect(260, 60, 3, 61))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.tab_4)
        self.line_6.setGeometry(QtCore.QRect(520, 60, 20, 61))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 190, 91, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(390, 190, 121, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(120, 180, 201, 27))
        self.lineEdit_11.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(540, 180, 201, 27))
        self.lineEdit_12.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.line_7 = QtGui.QFrame(self.tab_4)
        self.line_7.setGeometry(QtCore.QRect(360, 160, 3, 61))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.tab_4)
        self.line_8.setGeometry(QtCore.QRect(20, 220, 731, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(280, 20, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.line_9 = QtGui.QFrame(self.tab_4)
        self.line_9.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.checkBox = QtGui.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(30, 270, 99, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(150, 270, 471, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.line_10 = QtGui.QFrame(self.tab_4)
        self.line_10.setGeometry(QtCore.QRect(20, 430, 731, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(300, 240, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 450, 99, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.spinBox = QtGui.QSpinBox(self.tab_4)
        self.spinBox.setGeometry(QtCore.QRect(250, 310, 61, 27))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(30, 320, 131, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(170, 320, 131, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(30, 360, 571, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(30, 400, 571, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_3.setGeometry(QtCore.QRect(410, 80, 111, 27))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 120, 231, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(540, 120, 231, 27))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(600, 400, 99, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_27 = QtGui.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(280, 20, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.line_17 = QtGui.QFrame(self.tab_5)
        self.line_17.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.label_54 = QtGui.QLabel(self.tab_5)
        self.label_54.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.pushButton_15 = QtGui.QPushButton(self.tab_5)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 80, 121, 27))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.line_25 = QtGui.QFrame(self.tab_5)
        self.line_25.setGeometry(QtCore.QRect(260, 60, 3, 61))
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.label_55 = QtGui.QLabel(self.tab_5)
        self.label_55.setGeometry(QtCore.QRect(280, 90, 121, 17))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.line_42 = QtGui.QFrame(self.tab_5)
        self.line_42.setGeometry(QtCore.QRect(530, 60, 3, 61))
        self.line_42.setFrameShape(QtGui.QFrame.VLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName(_fromUtf8("line_42"))
        self.label_86 = QtGui.QLabel(self.tab_5)
        self.label_86.setGeometry(QtCore.QRect(550, 90, 101, 17))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.pushButton_24 = QtGui.QPushButton(self.tab_5)
        self.pushButton_24.setGeometry(QtCore.QRect(650, 80, 121, 27))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.label_87 = QtGui.QLabel(self.tab_5)
        self.label_87.setGeometry(QtCore.QRect(10, 190, 91, 17))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_21.setGeometry(QtCore.QRect(120, 180, 201, 27))
        self.lineEdit_21.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.line_43 = QtGui.QFrame(self.tab_5)
        self.line_43.setGeometry(QtCore.QRect(350, 160, 20, 61))
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.line_44 = QtGui.QFrame(self.tab_5)
        self.line_44.setGeometry(QtCore.QRect(20, 220, 721, 16))
        self.line_44.setFrameShape(QtGui.QFrame.HLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName(_fromUtf8("line_44"))
        self.label_89 = QtGui.QLabel(self.tab_5)
        self.label_89.setGeometry(QtCore.QRect(300, 240, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.tab_5)
        self.label_90.setGeometry(QtCore.QRect(20, 280, 151, 17))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.pushButton_25 = QtGui.QPushButton(self.tab_5)
        self.pushButton_25.setGeometry(QtCore.QRect(180, 270, 121, 27))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.label_91 = QtGui.QLabel(self.tab_5)
        self.label_91.setGeometry(QtCore.QRect(20, 380, 141, 17))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.lineEdit_22 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_22.setGeometry(QtCore.QRect(180, 410, 201, 27))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.label_92 = QtGui.QLabel(self.tab_5)
        self.label_92.setGeometry(QtCore.QRect(430, 380, 91, 17))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.lineEdit_23 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_23.setGeometry(QtCore.QRect(540, 370, 201, 27))
        self.lineEdit_23.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.line_45 = QtGui.QFrame(self.tab_5)
        self.line_45.setGeometry(QtCore.QRect(400, 370, 20, 81))
        self.line_45.setFrameShape(QtGui.QFrame.VLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName(_fromUtf8("line_45"))
        self.line_46 = QtGui.QFrame(self.tab_5)
        self.line_46.setGeometry(QtCore.QRect(20, 450, 721, 16))
        self.line_46.setFrameShape(QtGui.QFrame.HLine)
        self.line_46.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_46.setObjectName(_fromUtf8("line_46"))
        self.pushButton_26 = QtGui.QPushButton(self.tab_5)
        self.pushButton_26.setGeometry(QtCore.QRect(610, 460, 99, 27))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.label_93 = QtGui.QLabel(self.tab_5)
        self.label_93.setGeometry(QtCore.QRect(430, 420, 121, 17))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.tab_5)
        self.lcdNumber_2.setGeometry(QtCore.QRect(540, 410, 91, 31))
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.label_94 = QtGui.QLabel(self.tab_5)
        self.label_94.setGeometry(QtCore.QRect(20, 420, 101, 17))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.pushButton_27 = QtGui.QPushButton(self.tab_5)
        self.pushButton_27.setGeometry(QtCore.QRect(180, 370, 121, 27))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.comboBox_4 = QtGui.QComboBox(self.tab_5)
        self.comboBox_4.setGeometry(QtCore.QRect(410, 80, 111, 27))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.pushButton_32 = QtGui.QPushButton(self.tab_5)
        self.pushButton_32.setGeometry(QtCore.QRect(490, 460, 99, 27))
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.lineEdit_32 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_32.setGeometry(QtCore.QRect(10, 120, 231, 27))
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.lineEdit_33 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_33.setGeometry(QtCore.QRect(540, 120, 231, 27))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.textEdit = QtGui.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(20, 300, 721, 61))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lineEdit_34 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_34.setGeometry(QtCore.QRect(540, 270, 201, 27))
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.label_32 = QtGui.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(400, 280, 131, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_96 = QtGui.QLabel(self.tab_6)
        self.label_96.setGeometry(QtCore.QRect(350, 20, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_96.setFont(font)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.line_47 = QtGui.QFrame(self.tab_6)
        self.line_47.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.line_47.setFrameShape(QtGui.QFrame.HLine)
        self.line_47.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_47.setObjectName(_fromUtf8("line_47"))
        self.label_97 = QtGui.QLabel(self.tab_6)
        self.label_97.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.label_98 = QtGui.QLabel(self.tab_6)
        self.label_98.setGeometry(QtCore.QRect(20, 180, 68, 17))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.tab_6)
        self.label_99.setGeometry(QtCore.QRect(20, 130, 91, 17))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_101 = QtGui.QLabel(self.tab_6)
        self.label_101.setGeometry(QtCore.QRect(320, 310, 91, 17))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.lineEdit_24 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_24.setGeometry(QtCore.QRect(140, 70, 611, 27))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_25 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_25.setGeometry(QtCore.QRect(140, 120, 611, 27))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_26.setGeometry(QtCore.QRect(140, 170, 611, 27))
        self.lineEdit_26.setMaxLength(32768)
        self.lineEdit_26.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_26.setReadOnly(False)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.label_102 = QtGui.QLabel(self.tab_6)
        self.label_102.setGeometry(QtCore.QRect(20, 310, 101, 17))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.pushButton_28 = QtGui.QPushButton(self.tab_6)
        self.pushButton_28.setGeometry(QtCore.QRect(140, 300, 121, 27))
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.line_48 = QtGui.QFrame(self.tab_6)
        self.line_48.setGeometry(QtCore.QRect(20, 330, 731, 20))
        self.line_48.setFrameShape(QtGui.QFrame.HLine)
        self.line_48.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_48.setObjectName(_fromUtf8("line_48"))
        self.label_100 = QtGui.QLabel(self.tab_6)
        self.label_100.setGeometry(QtCore.QRect(370, 350, 68, 17))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.textEdit_8 = QtGui.QTextEdit(self.tab_6)
        self.textEdit_8.setGeometry(QtCore.QRect(30, 370, 721, 61))
        self.textEdit_8.setObjectName(_fromUtf8("textEdit_8"))
        self.line_49 = QtGui.QFrame(self.tab_6)
        self.line_49.setGeometry(QtCore.QRect(20, 430, 731, 20))
        self.line_49.setFrameShape(QtGui.QFrame.HLine)
        self.line_49.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_49.setObjectName(_fromUtf8("line_49"))
        self.pushButton_29 = QtGui.QPushButton(self.tab_6)
        self.pushButton_29.setGeometry(QtCore.QRect(640, 450, 99, 27))
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.lineEdit_35 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_35.setGeometry(QtCore.QRect(140, 220, 611, 27))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(420, 300, 331, 27))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_36 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_36.setGeometry(QtCore.QRect(140, 260, 611, 27))
        self.lineEdit_36.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.label_109 = QtGui.QLabel(self.tab_6)
        self.label_109.setGeometry(QtCore.QRect(20, 230, 68, 17))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.label_110 = QtGui.QLabel(self.tab_6)
        self.label_110.setGeometry(QtCore.QRect(20, 270, 81, 17))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.label_103 = QtGui.QLabel(self.tab_7)
        self.label_103.setGeometry(QtCore.QRect(350, 20, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_103.setFont(font)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.line_50 = QtGui.QFrame(self.tab_7)
        self.line_50.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.line_50.setFrameShape(QtGui.QFrame.HLine)
        self.line_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_50.setObjectName(_fromUtf8("line_50"))
        self.label_104 = QtGui.QLabel(self.tab_7)
        self.label_104.setGeometry(QtCore.QRect(20, 90, 131, 17))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.label_105 = QtGui.QLabel(self.tab_7)
        self.label_105.setGeometry(QtCore.QRect(20, 220, 121, 17))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.label_106 = QtGui.QLabel(self.tab_7)
        self.label_106.setGeometry(QtCore.QRect(20, 170, 111, 17))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_107 = QtGui.QLabel(self.tab_7)
        self.label_107.setGeometry(QtCore.QRect(20, 370, 181, 17))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.label_108 = QtGui.QLabel(self.tab_7)
        self.label_108.setGeometry(QtCore.QRect(20, 270, 171, 17))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.line_51 = QtGui.QFrame(self.tab_7)
        self.line_51.setGeometry(QtCore.QRect(20, 130, 731, 20))
        self.line_51.setFrameShape(QtGui.QFrame.HLine)
        self.line_51.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_51.setObjectName(_fromUtf8("line_51"))
        self.lineEdit_27 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_27.setGeometry(QtCore.QRect(220, 80, 241, 27))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.pushButton_30 = QtGui.QPushButton(self.tab_7)
        self.pushButton_30.setGeometry(QtCore.QRect(490, 80, 99, 27))
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.lineEdit_28 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_28.setGeometry(QtCore.QRect(220, 160, 241, 27))
        self.lineEdit_28.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.lineEdit_29 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_29.setGeometry(QtCore.QRect(220, 210, 241, 27))
        self.lineEdit_29.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.lineEdit_30 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_30.setGeometry(QtCore.QRect(220, 260, 241, 27))
        self.lineEdit_30.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.pushButton_31 = QtGui.QPushButton(self.tab_7)
        self.pushButton_31.setGeometry(QtCore.QRect(490, 260, 99, 27))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.line_52 = QtGui.QFrame(self.tab_7)
        self.line_52.setGeometry(QtCore.QRect(20, 320, 731, 20))
        self.line_52.setFrameShape(QtGui.QFrame.HLine)
        self.line_52.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_52.setObjectName(_fromUtf8("line_52"))
        self.lineEdit_31 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_31.setGeometry(QtCore.QRect(270, 360, 241, 27))
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.label_147 = QtGui.QLabel(self.tab_7)
        self.label_147.setGeometry(QtCore.QRect(220, 370, 31, 17))
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.pushButton_44 = QtGui.QPushButton(self.tab_7)
        self.pushButton_44.setGeometry(QtCore.QRect(560, 360, 99, 27))
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        self.label_148 = QtGui.QLabel(self.tab_7)
        self.label_148.setGeometry(QtCore.QRect(20, 420, 181, 17))
        self.label_148.setObjectName(_fromUtf8("label_148"))
        self.lineEdit_45 = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_45.setGeometry(QtCore.QRect(270, 410, 241, 27))
        self.lineEdit_45.setObjectName(_fromUtf8("lineEdit_45"))
        self.pushButton_45 = QtGui.QPushButton(self.tab_7)
        self.pushButton_45.setGeometry(QtCore.QRect(560, 410, 99, 27))
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.label_149 = QtGui.QLabel(self.tab_8)
        self.label_149.setGeometry(QtCore.QRect(350, 20, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_149.setFont(font)
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self.line_72 = QtGui.QFrame(self.tab_8)
        self.line_72.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.line_72.setFrameShape(QtGui.QFrame.HLine)
        self.line_72.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_72.setObjectName(_fromUtf8("line_72"))
        self.textEdit_17 = QtGui.QTextEdit(self.tab_8)
        self.textEdit_17.setGeometry(QtCore.QRect(223, 147, 531, 321))
        self.textEdit_17.setObjectName(_fromUtf8("textEdit_17"))
        self.pushButton_46 = QtGui.QPushButton(self.tab_8)
        self.pushButton_46.setGeometry(QtCore.QRect(20, 60, 99, 27))
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.pushButton_47 = QtGui.QPushButton(self.tab_8)
        self.pushButton_47.setGeometry(QtCore.QRect(650, 60, 99, 27))
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_8)
        self.textEdit_2.setGeometry(QtCore.QRect(33, 147, 181, 321))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_33 = QtGui.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(80, 110, 68, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.tab_8)
        self.label_34.setGeometry(QtCore.QRect(460, 110, 68, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.line_20 = QtGui.QFrame(self.tab_8)
        self.line_20.setGeometry(QtCore.QRect(20, 90, 731, 16))
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "USERNAME", None))
        self.label_2.setText(_translate("MainWindow", "PASSWORD", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your username", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter your password", None))
        self.pushButton.setText(_translate("MainWindow", "LOGIN", None))
        self.label_28.setText(_translate("MainWindow", "LOGIN", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "                                Login                                   ", None))
        self.label_4.setText(_translate("MainWindow", "FULL NAME", None))
        self.label_5.setText(_translate("MainWindow", "RE-TYPE PASSWORD", None))
        self.label_6.setText(_translate("MainWindow", "PASSWORD", None))
        self.label_7.setText(_translate("MainWindow", "USERNAME", None))
        self.label_8.setText(_translate("MainWindow", "E-MAIL", None))
        self.label_9.setText(_translate("MainWindow", "PHONE NUMBER", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "pick a username", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "choose a strong password", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "re-enter the password", None))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "enter your username", None))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "enter your full name", None))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "enter your mail ID", None))
        self.pushButton_3.setText(_translate("MainWindow", "REGISTER", None))
        self.label_29.setText(_translate("MainWindow", "REGISTER", None))
        self.label_38.setText(_translate("MainWindow", "Choose a strong password with a combination of upper case , lower case alphabets , special characters and numbers.", None))
        self.label_37.setText(_translate("MainWindow", "Note :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "                          Register                              ", None))
        self.pushButton_4.setText(_translate("MainWindow", "CONFIRM", None))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Enter the verification code here", None))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Enter the answer for the question given above", None))
        self.label_10.setText(_translate("MainWindow", "Answer :", None))
        self.label_11.setText(_translate("MainWindow", "Code :", None))
        self.pushButton_5.setText(_translate("MainWindow", "CONFIRM", None))
        self.label_12.setText(_translate("MainWindow", "Question :", None))
        self.label_30.setText(_translate("MainWindow", "ACCOUNT RECOVERY", None))
        self.label_13.setText(_translate("MainWindow", "Note : Please answer the question correctly to proceed further.", None))
        self.label_16.setText(_translate("MainWindow", " Please enter the code sent to your registered E-mail ID to gain access to your account.", None))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "Enter your User Name", None))
        self.label_31.setText(_translate("MainWindow", "Username :", None))
        self.pushButton_6.setText(_translate("MainWindow", "SEARCH", None))
        self.label_39.setText(_translate("MainWindow", "Note :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "        Account Recovery       ", None))
        self.label_3.setText(_translate("MainWindow", "ENCRYPTION/DECRYPTION SOFTWARE", None))
        self.pushButton_7.setText(_translate("MainWindow", "Choose file", None))
        self.label_14.setText(_translate("MainWindow", "File Explorer", None))
        self.label_15.setText(_translate("MainWindow", "Encryption Type", None))
        self.label_17.setText(_translate("MainWindow", "Target Folder", None))
        self.pushButton_8.setText(_translate("MainWindow", "Choose folder", None))
        self.label_18.setText(_translate("MainWindow", "Password", None))
        self.label_19.setText(_translate("MainWindow", "Re-type Password", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Enter password", None))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Re-Enter password", None))
        self.label_20.setText(_translate("MainWindow", "FILE ENCRYPTION", None))
        self.checkBox.setText(_translate("MainWindow", "Hide File", None))
        self.label_21.setText(_translate("MainWindow", "(Mark this box to hide the encrypted files from the current location )", None))
        self.label_22.setText(_translate("MainWindow", "Advanced Options", None))
        self.pushButton_2.setText(_translate("MainWindow", "Encrypt", None))
        self.label_23.setText(_translate("MainWindow", "Self Destruct File :", None))
        self.label_24.setText(_translate("MainWindow", "Count ", None))
        self.label_25.setText(_translate("MainWindow", "(choose a number to specify the number of trails before self destruction of the file )", None))
        self.label_26.setText(_translate("MainWindow", "Note : Advanced options are to be used only for highly sensitive information", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "AES ", None))
        self.pushButton_9.setText(_translate("MainWindow", "Hide", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "          Encryption         ", None))
        self.label_27.setText(_translate("MainWindow", "FILE DECRYPTION", None))
        self.label_54.setText(_translate("MainWindow", "File Explorer", None))
        self.pushButton_15.setText(_translate("MainWindow", "Choose file", None))
        self.label_55.setText(_translate("MainWindow", "Decryption Type", None))
        self.label_86.setText(_translate("MainWindow", "Target Folder", None))
        self.pushButton_24.setText(_translate("MainWindow", "Choose folder", None))
        self.label_87.setText(_translate("MainWindow", "Password", None))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "Enter password", None))
        self.label_89.setText(_translate("MainWindow", "Advanced Options", None))
        self.label_90.setText(_translate("MainWindow", "Hidden File Explorer", None))
        self.pushButton_25.setText(_translate("MainWindow", "Show files", None))
        self.label_91.setText(_translate("MainWindow", "Folder Explorer", None))
        self.label_92.setText(_translate("MainWindow", "Password :", None))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "Enter password", None))
        self.pushButton_26.setText(_translate("MainWindow", "Decrypt", None))
        self.label_93.setText(_translate("MainWindow", "Count", None))
        self.label_94.setText(_translate("MainWindow", "Target Folder", None))
        self.pushButton_27.setText(_translate("MainWindow", "Choose folder", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "AES ", None))
        self.pushButton_32.setText(_translate("MainWindow", "UnHide", None))
        self.lineEdit_34.setPlaceholderText(_translate("MainWindow", "Type the Chosen file name", None))
        self.label_32.setText(_translate("MainWindow", "Chosen File Name", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "           Decryption            ", None))
        self.label_96.setText(_translate("MainWindow", "MAILER", None))
        self.label_97.setText(_translate("MainWindow", "Sender e-mail :", None))
        self.label_98.setText(_translate("MainWindow", "Subject :", None))
        self.label_99.setText(_translate("MainWindow", "Recepients :", None))
        self.label_101.setText(_translate("MainWindow", "Chosen FIle :", None))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "enter your mail ID", None))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "enter the receiver\'s mail ID", None))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "Subject of your Mail", None))
        self.label_102.setText(_translate("MainWindow", "File Explorer :", None))
        self.pushButton_28.setText(_translate("MainWindow", "Choose file", None))
        self.label_100.setText(_translate("MainWindow", "STATUS", None))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">nil</p></body></html>", None))
        self.pushButton_29.setText(_translate("MainWindow", "Send", None))
        self.lineEdit_35.setPlaceholderText(_translate("MainWindow", "Body of the Mail", None))
        self.lineEdit_36.setPlaceholderText(_translate("MainWindow", "Enter your password", None))
        self.label_109.setText(_translate("MainWindow", "Body :", None))
        self.label_110.setText(_translate("MainWindow", "Password :", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "             Share               ", None))
        self.label_103.setText(_translate("MainWindow", "SETTINGS", None))
        self.label_104.setText(_translate("MainWindow", " Full Name  :", None))
        self.label_105.setText(_translate("MainWindow", "New Password :", None))
        self.label_106.setText(_translate("MainWindow", "Old Password :", None))
        self.label_107.setText(_translate("MainWindow", "Recovery Phone Number :", None))
        self.label_108.setText(_translate("MainWindow", "Re-type New Password :", None))
        self.pushButton_30.setText(_translate("MainWindow", "Change", None))
        self.pushButton_31.setText(_translate("MainWindow", "Change", None))
        self.label_147.setText(_translate("MainWindow", "+91", None))
        self.pushButton_44.setText(_translate("MainWindow", "Change", None))
        self.label_148.setText(_translate("MainWindow", "Default E-mail :", None))
        self.pushButton_45.setText(_translate("MainWindow", "Change", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "             Settings              ", None))
        self.label_149.setText(_translate("MainWindow", "HISTORY", None))
        self.pushButton_46.setText(_translate("MainWindow", "Show History", None))
        self.pushButton_47.setText(_translate("MainWindow", "Clear History", None))
        self.label_33.setText(_translate("MainWindow", "TIME", None))
        self.label_34.setText(_translate("MainWindow", "FEED", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "          History           ", None))

import start_rc
